Repository jbt-it/neomdb, pull requests merged in 2020-04, with the labels that each got.

#36 Added some windows env support
  CONTRIBUTING.md
Labels: enhancement

#41 #40 extend member overview
  server/src/members/membersController.ts
Labels: enhancement

#45 Added correct routing for the Frontend
  client/package-lock.json
  client/package.json
  client/src/ts/global/App.tsx
  client/src/ts/global/NotFound.test.tsx
  client/src/ts/global/NotFound.tsx
  client/src/ts/global/navigation/MenuDrawer.tsx
  client/src/ts/members/Login.tsx
Labels: enhancement

#49 Changed the route to the NotFound component to a private route
  client/src/ts/global/App.tsx
Labels: bug

#50 #14 add member overview
  client/src/scss/app.scss
  client/src/ts/global/App.tsx
  client/src/ts/members/MemberOverview.tsx
Labels: feature request

#56 Modified login to return an object
  client/src/ts/members/Login.tsx
  server/src/members/membersController.ts
Labels: enhancement
